
export type TransactionType = 'contribution' | 'withdrawal' | 'interest' | 'transfer_in' | 'transfer_out';

export interface Transaction {
  id: string;
  contributionDate: string; // ISO string YYYY-MM-DD (The "For" Date)
  transactionDate: string; // ISO string YYYY-MM-DD (The "On" Date - used for calculation)
  amount: number;
  type: TransactionType;
  description: string;
  isAutoGenerated?: boolean;
}

export interface UserProfile {
  employerName: string;
  joiningDate: string; // YYYY-MM-DD
  endDate: string; // YYYY-MM-DD (Empty if current)
  targetDate: string; // For estimation
}

// Used for the Batch Generator UI
export interface YearConfig {
  year: number; // Start year of FY (e.g. 2022 for FY22-23)
  monthlyContribution: number;
  interestRate: number;
}

export interface MonthlyBalance {
  monthName: string;
  year: number;
  openingBalance: number;
  totalCredits: number;
  totalDebits: number;
  interestAccrued: number;
  closingBalance: number;
}

export interface FinancialYearRecord {
  startYear: number; // Explicit start year (e.g. 2022)
  label: string; // e.g., "FY2022-23"
  startDate: string;
  endDate: string;
  openingBalance: number;
  totalContributions: number;
  totalWithdrawals: number;
  interestRate: number;
  interestEarned: number;
  closingBalance: number;
  isProjected: boolean;
  monthlyBreakdown: MonthlyBalance[];
}

export interface AppData {
  profile: UserProfile;
  transactions: Transaction[];
  // We store the interest rates map separately to persist user preferences for each year
  interestRates: Record<number, number>; 
}

export interface YearlySummary {
  openingBalance: number;
  totalContribution: number;
  totalWithdrawal: number;
  totalInterest: number;
  closingBalance: number;
}

export interface Withdrawal {
  id: string;
  monthIndex: number;
  amount: number;
  description: string;
}

export interface EPFInputState {
  currentBalance: number;
  monthlyContribution: number;
  interestRate: number;
  withdrawals: Withdrawal[];
}

export interface MonthlyData {
  monthName: string;
  openingBalance: number;
  contribution: number;
  withdrawal: number;
  interestEarned: number;
  closingBalance: number;
}
