import React, { useState, useMemo } from 'react';
import { Transaction, TransactionType } from '../types';
import { Plus, Trash2, ArrowUpCircle, ArrowDownCircle, Edit2, Check, X, Ban, Calendar, IndianRupee, Clock, Search, Filter, ChevronLeft, ChevronRight, ArrowUpDown, ArrowUp, ArrowDown } from 'lucide-react';

interface Props {
  transactions: Transaction[];
  onAddTransaction: (t: Transaction) => void;
  onUpdateTransaction: (t: Transaction) => void;
  onDeleteTransaction: (id: string) => void;
}

type SortKey = 'contributionDate' | 'amount';
type SortDirection = 'asc' | 'desc';

const TransactionManager: React.FC<Props> = ({ transactions, onAddTransaction, onUpdateTransaction, onDeleteTransaction }) => {
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingId, setEditingId] = useState<string | null>(null);
  
  // Table Features State
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(12);
  const [sortConfig, setSortConfig] = useState<{ key: SortKey; direction: SortDirection }>({ key: 'contributionDate', direction: 'desc' });
  const [filterType, setFilterType] = useState<string>('all');
  const [searchQuery, setSearchQuery] = useState('');

  const [formData, setFormData] = useState({
    contributionDate: new Date().toISOString().split('T')[0],
    transactionDate: new Date().toISOString().split('T')[0],
    type: 'contribution' as TransactionType,
    description: '',
    amount: ''
  });

  // Filter, Sort, and Paginate Logic
  const processedData = useMemo(() => {
    let result = [...transactions];

    // 1. Filtering
    if (filterType !== 'all') {
      if (filterType === 'credit') {
        result = result.filter(t => ['contribution', 'transfer_in', 'interest'].includes(t.type));
      } else if (filterType === 'debit') {
        result = result.filter(t => ['withdrawal', 'transfer_out'].includes(t.type));
      } else {
        result = result.filter(t => t.type === filterType);
      }
    }

    if (searchQuery.trim()) {
      const q = searchQuery.toLowerCase();
      result = result.filter(t => 
        t.description.toLowerCase().includes(q) || 
        t.amount.toString().includes(q)
      );
    }

    // 2. Sorting
    result.sort((a, b) => {
      let valA: any = a[sortConfig.key];
      let valB: any = b[sortConfig.key];

      if (sortConfig.key === 'contributionDate') {
        valA = new Date(valA).getTime();
        valB = new Date(valB).getTime();
      }

      if (valA < valB) return sortConfig.direction === 'asc' ? -1 : 1;
      if (valA > valB) return sortConfig.direction === 'asc' ? 1 : -1;
      return 0;
    });

    return result;
  }, [transactions, filterType, searchQuery, sortConfig]);

  const totalItems = processedData.length;
  const totalPages = Math.ceil(totalItems / pageSize);
  const paginatedTransactions = processedData.slice((currentPage - 1) * pageSize, currentPage * pageSize);

  const handleSort = (key: SortKey) => {
    setSortConfig(current => ({
      key,
      direction: current.key === key && current.direction === 'desc' ? 'asc' : 'desc'
    }));
  };

  const resetForm = () => {
    const today = new Date().toISOString().split('T')[0];
    setFormData({
      contributionDate: today,
      transactionDate: today,
      type: 'contribution',
      description: '',
      amount: ''
    });
    setEditingId(null);
    setIsModalOpen(false);
  };

  const handleStartAdd = () => {
    resetForm();
    setIsModalOpen(true);
    setEditingId(null);
  };

  const handleStartEdit = (t: Transaction) => {
    setFormData({
      contributionDate: t.contributionDate,
      transactionDate: t.transactionDate,
      type: t.type,
      description: t.description,
      amount: t.amount.toString()
    });
    setEditingId(t.id);
    setIsModalOpen(true);
  };

  const handleSave = () => {
    const amountVal = parseFloat(formData.amount);
    
    // Validation
    if (!formData.contributionDate || !formData.transactionDate || isNaN(amountVal) || amountVal <= 0) {
      alert("Please enter valid dates and a positive amount.");
      return;
    }

    const tx: Transaction = {
      id: editingId || `tx-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      contributionDate: formData.contributionDate,
      transactionDate: formData.transactionDate,
      amount: amountVal,
      type: formData.type,
      description: formData.description || (formData.type === 'contribution' ? 'Contribution' : 'Withdrawal'),
      isAutoGenerated: false
    };

    if (editingId) {
      onUpdateTransaction(tx);
    } else {
      onAddTransaction(tx);
    }
    
    resetForm();
  };

  return (
    <div className="space-y-6 pb-20">
      <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-4">
         <div>
            <h2 className="text-2xl font-bold text-slate-800">Transactions Ledger</h2>
            <p className="text-slate-500 text-sm">Manage individual credits and withdrawals</p>
         </div>
         <button 
           onClick={handleStartAdd}
           className="bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-700 hover:to-indigo-700 text-white px-5 py-2.5 rounded-xl shadow-lg shadow-indigo-200 flex items-center gap-2 text-sm font-bold transition-all transform hover:-translate-y-0.5"
         >
           <Plus size={18} /> Add New Entry
         </button>
      </div>

      {/* Toolbar */}
      <div className="bg-white p-4 rounded-2xl border border-slate-100 shadow-sm flex flex-col md:flex-row gap-4 items-center justify-between">
        <div className="flex flex-1 w-full md:w-auto gap-4">
           {/* Search */}
           <div className="relative flex-1 md:max-w-xs">
              <Search className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
              <input 
                 type="text" 
                 placeholder="Search transactions..." 
                 value={searchQuery}
                 onChange={(e) => { setSearchQuery(e.target.value); setCurrentPage(1); }}
                 className="w-full pl-10 pr-4 py-2 bg-slate-50 border border-slate-200 rounded-lg text-sm focus:ring-2 focus:ring-violet-500 focus:border-violet-500 outline-none transition-all"
              />
           </div>
           
           {/* Filter */}
           <div className="relative min-w-[140px]">
              <div className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-500 pointer-events-none">
                 <Filter size={16} />
              </div>
              <select
                 value={filterType}
                 onChange={(e) => { setFilterType(e.target.value); setCurrentPage(1); }}
                 className="w-full pl-9 pr-8 py-2 bg-slate-50 border border-slate-200 rounded-lg text-sm appearance-none focus:ring-2 focus:ring-violet-500 outline-none cursor-pointer text-slate-700 font-medium"
              >
                 <option value="all">All Types</option>
                 <option value="contribution">Contributions</option>
                 <option value="withdrawal">Withdrawals</option>
                 <option value="interest">Interest</option>
                 <option value="credit">All Credits</option>
                 <option value="debit">All Debits</option>
              </select>
           </div>
        </div>

        <div className="flex items-center gap-2 text-sm text-slate-500">
           <span>Show</span>
           <select 
              value={pageSize}
              onChange={(e) => { setPageSize(Number(e.target.value)); setCurrentPage(1); }}
              className="bg-slate-50 border border-slate-200 rounded-lg py-1.5 px-2 focus:ring-2 focus:ring-violet-500 outline-none font-medium"
           >
              <option value="12">12</option>
              <option value="24">24</option>
              <option value="48">48</option>
              <option value="1000">All</option>
           </select>
        </div>
      </div>

      <div className="bg-white rounded-2xl border border-slate-100 shadow-xl shadow-slate-200/50 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="bg-slate-50/80 text-slate-500 border-b border-slate-200">
              <tr>
                <th className="px-6 py-4 font-semibold uppercase tracking-wider text-xs cursor-pointer hover:bg-slate-100 transition-colors" onClick={() => handleSort('contributionDate')}>
                  <div className="flex items-center gap-2">
                    Contribution Month
                    {sortConfig.key === 'contributionDate' ? (
                       sortConfig.direction === 'asc' ? <ArrowUp size={14}/> : <ArrowDown size={14}/>
                    ) : <ArrowUpDown size={14} className="opacity-30" />}
                  </div>
                </th>
                <th className="px-6 py-4 font-semibold uppercase tracking-wider text-xs">Type</th>
                <th className="px-6 py-4 font-semibold uppercase tracking-wider text-xs">Description</th>
                <th className="px-6 py-4 font-semibold uppercase tracking-wider text-xs text-right cursor-pointer hover:bg-slate-100 transition-colors" onClick={() => handleSort('amount')}>
                   <div className="flex items-center justify-end gap-2">
                    Amount (₹)
                    {sortConfig.key === 'amount' ? (
                       sortConfig.direction === 'asc' ? <ArrowUp size={14}/> : <ArrowDown size={14}/>
                    ) : <ArrowUpDown size={14} className="opacity-30" />}
                  </div>
                </th>
                <th className="px-6 py-4 font-semibold uppercase tracking-wider text-xs text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              
              {paginatedTransactions.length === 0 && (
                 <tr>
                   <td colSpan={5} className="text-center py-16 text-slate-400">
                     <div className="flex flex-col items-center gap-3">
                        <div className="bg-slate-100 p-4 rounded-full">
                           <Calendar size={32} className="text-slate-300"/>
                        </div>
                        <p className="font-medium">No transactions found matching your filters.</p>
                     </div>
                   </td>
                 </tr>
              )}

              {paginatedTransactions.map((t) => {
                const isCredit = t.type === 'contribution' || t.type === 'transfer_in' || t.type === 'interest';
                
                return (
                  <tr key={t.id} className="hover:bg-slate-50 group transition-colors">
                    <td className="px-6 py-4 text-slate-700 whitespace-nowrap font-medium">
                      <div className="flex flex-col">
                        <span>{new Date(t.contributionDate).toLocaleDateString('en-IN', { year: 'numeric', month: 'short', day: 'numeric' })}</span>
                        {t.transactionDate !== t.contributionDate && (
                           <span className="text-[10px] text-slate-400 flex items-center gap-1">
                             <Clock size={10} /> Paid: {new Date(t.transactionDate).toLocaleDateString('en-IN', { month: 'short', day: 'numeric' })}
                           </span>
                        )}
                      </div>
                    </td>
                    <td className="px-6 py-4">
                      <span className={`inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-bold border ${isCredit ? 'bg-indigo-50 text-indigo-700 border-indigo-100' : 'bg-rose-50 text-rose-700 border-rose-100'}`}>
                        {isCredit ? <ArrowUpCircle size={14}/> : <ArrowDownCircle size={14}/>}
                        {t.type.replace('_', ' ').toUpperCase()}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-slate-600 font-medium">
                      {t.description}
                      {t.isAutoGenerated && <span className="ml-2 text-[10px] bg-slate-100 text-slate-400 px-1.5 py-0.5 rounded border border-slate-200 font-normal">AUTO</span>}
                    </td>
                    <td className={`px-6 py-4 text-right font-bold text-base ${isCredit ? 'text-indigo-600' : 'text-rose-500'}`}>
                      {isCredit ? '+' : '-'} {t.amount.toLocaleString('en-IN')}
                    </td>
                    <td className="px-6 py-4 text-right">
                      <div className="flex items-center justify-end gap-2 opacity-60 group-hover:opacity-100 transition-opacity">
                         <button onClick={() => handleStartEdit(t)} title="Edit" className="p-2 text-slate-400 hover:text-indigo-600 hover:bg-indigo-50 rounded-lg transition-all">
                           <Edit2 size={16} />
                         </button>
                         <button onClick={() => onDeleteTransaction(t.id)} title="Delete" className="p-2 text-slate-400 hover:text-rose-600 hover:bg-rose-50 rounded-lg transition-all">
                           <Trash2 size={16} />
                         </button>
                      </div>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
        
        {/* Pagination Footer */}
        {totalItems > 0 && (
          <div className="px-6 py-4 border-t border-slate-100 flex flex-col md:flex-row items-center justify-between gap-4 bg-slate-50/30">
             <div className="text-sm text-slate-500">
                Showing <span className="font-bold text-slate-800">{Math.min((currentPage - 1) * pageSize + 1, totalItems)}</span> to <span className="font-bold text-slate-800">{Math.min(currentPage * pageSize, totalItems)}</span> of <span className="font-bold text-slate-800">{totalItems}</span> transactions
             </div>
             
             <div className="flex items-center gap-2">
                <button 
                  onClick={() => setCurrentPage(prev => Math.max(prev - 1, 1))}
                  disabled={currentPage === 1}
                  className="p-2 border border-slate-200 rounded-lg text-slate-600 hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                   <ChevronLeft size={16} />
                </button>
                <div className="flex items-center gap-1">
                   {Array.from({length: Math.min(5, totalPages)}, (_, i) => {
                      // Logic to show pages around current page could be complex, simplifying to show first 5 or logic around current
                      let p = i + 1;
                      if (totalPages > 5) {
                         if (currentPage > 3) p = currentPage - 2 + i;
                         if (p > totalPages) p = totalPages - 4 + i;
                      }
                      
                      // Safety check
                      if (p > totalPages || p < 1) return null;

                      return (
                         <button 
                           key={p}
                           onClick={() => setCurrentPage(p)}
                           className={`w-8 h-8 rounded-lg text-sm font-semibold transition-colors ${currentPage === p ? 'bg-violet-600 text-white shadow-md shadow-violet-200' : 'text-slate-600 hover:bg-slate-100'}`}
                         >
                           {p}
                         </button>
                      );
                   })}
                </div>
                <button 
                  onClick={() => setCurrentPage(prev => Math.min(prev + 1, totalPages))}
                  disabled={currentPage === totalPages}
                  className="p-2 border border-slate-200 rounded-lg text-slate-600 hover:bg-white disabled:opacity-50 disabled:cursor-not-allowed transition-colors"
                >
                   <ChevronRight size={16} />
                </button>
             </div>
          </div>
        )}
      </div>

      {/* MODAL POPUP */}
      {isModalOpen && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 backdrop-blur-sm p-4 animate-in fade-in duration-200">
           <div className="bg-white rounded-2xl shadow-2xl w-full max-w-md overflow-hidden animate-in zoom-in-95 duration-200">
              <div className="bg-slate-50 px-6 py-4 border-b border-slate-100 flex justify-between items-center">
                 <h3 className="font-bold text-lg text-slate-800">{editingId ? 'Edit Transaction' : 'New Transaction'}</h3>
                 <button onClick={resetForm} className="text-slate-400 hover:text-slate-600">
                   <X size={20} />
                 </button>
              </div>
              
              <div className="p-6 space-y-4">
                 
                 <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-2">
                        <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Contribution Month</label>
                        <div className="relative">
                        <Calendar className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} />
                        <input 
                            type="date" 
                            value={formData.contributionDate}
                            onChange={e => setFormData({...formData, contributionDate: e.target.value})}
                            className="w-full pl-9 pr-2 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:border-violet-500 outline-none transition-all font-medium text-slate-700 text-xs"
                        />
                        </div>
                        <p className="text-[10px] text-slate-400">The wage month (e.g., April)</p>
                    </div>

                    <div className="space-y-2">
                        <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Transaction Date</label>
                        <div className="relative">
                        <Clock className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={16} />
                        <input 
                            type="date" 
                            value={formData.transactionDate}
                            onChange={e => setFormData({...formData, transactionDate: e.target.value})}
                            className="w-full pl-9 pr-2 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:border-violet-500 outline-none transition-all font-medium text-slate-700 text-xs"
                        />
                        </div>
                        <p className="text-[10px] text-slate-400">When money hit the account</p>
                    </div>
                 </div>

                 <div className="space-y-2">
                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Type</label>
                    <div className="grid grid-cols-2 gap-2">
                       <button 
                         onClick={() => setFormData({...formData, type: 'contribution'})}
                         className={`py-2 rounded-lg text-sm font-semibold border ${formData.type === 'contribution' ? 'bg-indigo-50 border-indigo-200 text-indigo-700' : 'border-slate-200 text-slate-500 hover:bg-slate-50'}`}
                       >
                         Credit (+)
                       </button>
                       <button 
                         onClick={() => setFormData({...formData, type: 'withdrawal'})}
                         className={`py-2 rounded-lg text-sm font-semibold border ${formData.type === 'withdrawal' ? 'bg-rose-50 border-rose-200 text-rose-700' : 'border-slate-200 text-slate-500 hover:bg-slate-50'}`}
                       >
                         Debit (-)
                       </button>
                    </div>
                 </div>

                 <div className="space-y-2">
                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Amount</label>
                    <div className="relative">
                      <IndianRupee className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" size={18} />
                      <input 
                        type="number" 
                        value={formData.amount}
                        onChange={e => setFormData({...formData, amount: e.target.value})}
                        placeholder="0.00"
                        className="w-full pl-10 pr-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:border-violet-500 outline-none transition-all font-bold text-lg text-slate-800"
                      />
                    </div>
                 </div>

                 <div className="space-y-2">
                    <label className="text-xs font-bold text-slate-500 uppercase tracking-wider">Description</label>
                    <input 
                      type="text" 
                      value={formData.description}
                      onChange={e => setFormData({...formData, description: e.target.value})}
                      placeholder={formData.type === 'contribution' ? "e.g. Monthly Contribution" : "e.g. Medical Withdrawal"}
                      className="w-full px-4 py-3 bg-white border border-slate-200 rounded-xl focus:ring-2 focus:ring-violet-500 focus:border-violet-500 outline-none transition-all font-medium text-slate-700"
                    />
                 </div>
              </div>

              <div className="p-6 border-t border-slate-100 flex gap-3">
                 <button onClick={resetForm} className="flex-1 py-3 text-slate-600 font-bold hover:bg-slate-50 rounded-xl transition-colors">
                   Cancel
                 </button>
                 <button onClick={handleSave} className="flex-1 py-3 bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-700 hover:to-indigo-700 text-white font-bold rounded-xl shadow-lg shadow-indigo-200 transition-all transform active:scale-95">
                   {editingId ? 'Save Changes' : 'Add Transaction'}
                 </button>
              </div>
           </div>
        </div>
      )}
    </div>
  );
};

export default TransactionManager;